##################################################################
#              Docker Compose file that starts Kong              #
##################################################################
version: '2.1'

services:
    # Load Balancing
    consul:
      image: progrium/consul:latest
      command: -server -bootstrap -ui-dir /ui
      restart: always
      mem_limit: 128m
      ports:
        - 8500:8500
      expose:
        - 53
        - 8300
        - 8301
        - 8302
        - 8400
        - 8500
      dns:
        - 127.0.0.1

    nginx-lb:
      build: nginx/
      mem_limit: 128m
      ports:
        - 8000:8000
        - 8443:8443
        - 1337:1337
      expose:
        - 8000
        - 8443
        - 8001
        - 1337
      links:
        - consul:consul
      restart: always
      command: >
          /bin/containerpilot
          -config file:///etc/containerpilot/containerpilot.json
          nginx -g "daemon off;"

    # Kong Database

    kong-database:
      image: postgres:9.6-alpine
      ports:
        - 5432
      expose:
        - 5432
      environment:
        - POSTGRES_USER=kong
        - POSTGRES_DB=kong
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

    kong-migration:
      image: kong:0.14.1-alpine
      depends_on:
        kong-database:
          condition: service_healthy
      environment:
        - KONG_DATABASE=postgres
        - KONG_PG_HOST=kong-database
      command: kong migrations up


    kong:
      build: kong/
      restart: always
      depends_on:
        kong-migration:
          condition: service_started
      links:
        - kong-database:kong-database
        - consul
      expose:
        - 7946
        - 7946/udp
        - 8000
        - 8001
        - 8443
      environment:
        - KONG_DATABASE=postgres
        - KONG_PG_HOST=kong-database
      healthcheck:
        test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
        interval: 5s
        retries: 10

    konga:
      build: konga/
      restart: always
      links:
        - kong:kong
        - kong-database:kong-database
        - consul
      environment:
        - NODE_ENV=development
        - DB_ADAPTER=postgres
        - DB_HOST=kong-database
        - DB_USER=kong
        - DB_DATABASE=kong
        - DB_PORT=5432
      expose:
        - 1337
